import type { CliCommandResult } from '../types/index.js';

function block(lines: string[]) {
  return lines.join('\n');
}

export function getHelpResult(command?: string): CliCommandResult {
  if (command === 'ask') {
    return {
      ok: true,
      message: block([
        'Kiipu CLI',
        '',
        'Usage:',
        '  kiipu ask "question"',
        '  kiipu ask --question "question"',
        '  kiipu ask --conversation-id <conversationId> "follow-up"',
        '  kiipu ask history [--query <q>] [--limit <n>] [--archived]',
        '  kiipu ask show --id <conversationId>',
        '',
        'Description:',
        '  Ask questions over your Kiipu notes using the same conversation-aware Ask surface as the web app.',
        '',
        'Options:',
        '  --question "<text>"        Question to ask when not using a positional argument',
        '  --conversation-id <id>     Continue an existing Ask conversation',
        '  --top-k <1-20>             Optional retrieval count for Ask',
        '  --source-mode <value>      One of fresh or locked',
        '  --query "<query>"          Filter Ask history rows',
        '  --limit <1-50>             Limit Ask history rows',
        '  --archived                 List archived Ask conversations',
        '  --id <conversationId>      Conversation id for ask show',
        '',
        'Examples:',
        '  kiipu ask "What did I save about the roadmap?"',
        '  kiipu ask --conversation-id conv_123 "What should I do next?"',
        '  kiipu ask history --limit 10',
        '  kiipu ask show --id conv_123',
      ]),
    };
  }

  if (command === 'note') {
    return {
      ok: true,
      message: block([
        'Kiipu CLI',
        '',
        'Usage:',
        '  kiipu note create --content "<text>" [--title "<title>"]',
        '  kiipu note create "<text>" [--title "<title>"]',
        '  kiipu note list [--tag <tag>] [--sort <updatedAt|createdAt|title>] [--starred] [--deleted]',
        '  kiipu note search <query>',
        '  kiipu note search --query "<query>"',
        '  kiipu note show --id <noteId>',
        '  kiipu note update --id <noteId> --content "<text>" [--title "<title>"] [--visibility public|private]',
        '  kiipu note star --id <noteId>',
        '  kiipu note pin --id <noteId>',
        '  kiipu note delete --id <noteId>',
        '  kiipu note restore --id <noteId>',
        '  kiipu note purge --id <noteId>',
        '',
        'Description:',
        '  Run direct Kiipu note actions from the local CLI.',
        '',
        'Actions:',
        '  create      Create a new note',
        '  list        List your active, starred, or deleted notes',
        '  search      Search your active notes',
        '  show        Show one note with full metadata',
        '  update      Update note content and metadata',
        '  star        Toggle a note star',
        '  pin         Toggle a note pin',
        '  delete      Soft-delete an existing note by explicit id',
        '  restore     Restore a deleted note by explicit id',
        '  purge       Permanently delete a note by explicit id',
        '',
        'Options:',
        '  --content "<text>"         Note content for create',
        '  --id <noteId>              Required for show, update, star, pin, delete, restore, and purge',
        '  --query "<query>"          Search query for note search',
        '  --tag <tag>                Filter note list results by tag',
        '  --sort <field>             One of updatedAt, createdAt, or title',
        '  --starred                  List only starred notes',
        '  --deleted                  List only deleted notes',
        '  --title "<title>"          Optional title for note create or update',
        '  --visibility <value>       Optional visibility for note update',
        '  Tags are derived from #tag tokens in note content',
        '',
        'Examples:',
        '  kiipu note create "Hello Kiipu" --title "Welcome"',
        '  kiipu note list --sort updatedAt',
        '  kiipu note search "roadmap"',
        '  kiipu note show --id 123',
        '  kiipu note update --id 123 --content "Updated text #work #notes"',
        '  kiipu note star --id 123',
        '  kiipu note pin --id 123',
        '  kiipu note create --content "Hello Kiipu"',
        '  kiipu note delete --id 123',
        '  kiipu note restore --id 123',
      ]),
    };
  }

  if (command === 'skills') {
    return {
      ok: true,
      message: block([
        'Kiipu CLI',
        '',
        'Skills:',
        '  Claude Code plugin support is published from the separate `@kiipu/claude-plugin` package.',
        '',
        'Examples:',
        '  kiipu skills',
        '  npm view @kiipu/claude-plugin version',
        '  claude --plugin-dir ./packages/claude-plugin',
      ]),
    };
  }

  if (command === 'auth') {
    return {
      ok: true,
      message: block([
        'Kiipu CLI',
        '',
        'Usage:',
        '  kiipu auth login',
        '  kiipu auth login --device-name "<name>"',
        '  kiipu auth login --no-browser',
        '  kiipu auth login --api-key <cpk_...>',
        '  kiipu auth status',
        '  kiipu auth logout',
        '',
        'Description:',
        '  Manage local Kiipu authentication. Browser login is the default flow.',
        '',
        'Options:',
        '  --device-name "<name>" Name shown under Connected Devices for browser login.',
        '  --no-browser          Print the browser login URL instead of opening it automatically.',
        '  --api-key <cpk_...>   Manually store an existing API key for compatibility or CI.',
        '',
        'Examples:',
        '  kiipu auth login',
        '  kiipu auth login --device-name "MacBook Pro"',
        '  kiipu auth login --no-browser',
        '  kiipu auth login --api-key cpk_abc123...',
        '  kiipu auth status',
        '  kiipu auth logout',
      ]),
    };
  }

  if (command === 'doctor') {
    return {
      ok: true,
      message: block([
        'Kiipu CLI',
        '',
        'Usage:',
        '  kiipu doctor',
        '',
        'Description:',
        '  Inspect local setup and API reachability for the local CLI.',
        '',
        'Checks:',
        '  - local Kiipu config exists',
        '  - production API health and API key auth are reachable by default',
        '  - KIIPU_API_URL can explicitly override the API base URL for local development',
      ]),
    };
  }

  return {
    ok: true,
    message: block([
      'Kiipu CLI',
      '',
      'Usage:',
      '  kiipu <command> [options]',
      '',
      'Core commands:',
      '  ask                Ask questions over your Kiipu notes and browse Ask conversations',
      '  note               Create, browse, update, and delete notes with direct CLI arguments',
      '  auth               Manage local API key authentication',
      '  doctor             Check local setup, API access, and wrapper readiness',
      '  skills             Show where the Claude Code plugin package lives',
      '',
      'Core examples:',
      '  kiipu ask "What changed in my roadmap notes?"',
      '  kiipu ask history --limit 10',
      '  kiipu note create "Hello Kiipu"',
      '  kiipu note list --starred',
      '  kiipu note search "Hello"',
      '  kiipu note delete --id 123',
      '  kiipu auth login',
      '  kiipu doctor',
      '  claude --plugin-dir ./packages/claude-plugin',
      '  KIIPU_API_URL=http://localhost:3001 kiipu doctor',
      '',
      'Claude Code plugin:',
      '  kiipu skills',
      '',
      'Global options:',
      '  --json             Print structured JSON instead of plain text',
      '  -v, --version     Show the current CLI version',
      '  -h, --help        Show help for the root CLI or a subcommand',
      '',
      'Help:',
      '  kiipu -v',
      '  kiipu --help',
      '  kiipu -h',
      '  kiipu <command> --help',
    ]),
  };
}
